name: BaimoInvSee
version: 1.0.1
main: top.baimoqilin.BaimoInvSee.BaimoInvSee
api: 1.0.0
author: BaimoQilin
description: A PowerNukkitX plugin that allows OPs to view and modify player inventories.
commands:
  baimoinvsee:
    description: View and modify a player's inventory
    usage: /baimoinvsee <player_name>
    permission: baimoinvsee.command
  baimoinvconfig:
    description: Configure inventory saving interval
    usage: /baimoinvconfig <interval_in_minutes>
    permission: baimoinvsee.config
permissions:
  baimoinvsee.command:
    description: Allows the user to use the /baimoinvsee command
    default: op
  baimoinvsee.config:
    description: Allows the user to use the /baimoinvconfig command
    default: op
